In [1]:
import pandas as pd

dataset = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin1")
dataset.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [2]:
dataset["order date (DateOrders)"] = pd.to_datetime(dataset["order date (DateOrders)"])
# dataset["order date (DateOrders)"]

In [3]:
dataset["shipping date (DateOrders)"] = pd.to_datetime(dataset["shipping date (DateOrders)"])

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  datetime64[ns]
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 52  Shipping Mode                  180519 non-null  object
dtypes: datetime64[ns](2), float64(15), int64(14), object(22)
memory usage: 73.0+ MB

In [5]:
dataset.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [6]:
dataset.drop("Order Zipcode", axis=1, inplace=True)
dataset.drop("Product Description", axis=1, inplace=True)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  datetime64[ns]
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Product Card Id                180519 non-null  int64
 44  Product Category Id            180519 non-null  int64
 45  Product Image                  180519 non-null  object
 46  Product Name                   180519 non-null  object
 47  Product Price                  180519 non-null  float64
 48  Product Status                 180519 non-null  int64
 49  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 50  Shipping Mode                  180519 non-null  object
dtypes: datetime64[ns](2), float64(13), int64(14), object(22)
memory usage: 70.2+ MB

In [7]:
dataset = dataset[dataset["Delivery Status"] != "Shipping canceled"]
dataset.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,Guangdong,COMPLETE,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 10:42:00,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,Guangdong,PROCESSING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 10:21:00,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,Guangdong,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 10:00:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,Guangdong,CLOSED,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 09:39:00,First Class
11,TRANSFER,5,2,45.689999,268.760010,Late delivery,1,73,Sporting Goods,Freeport,...,Célebes Septentrional,PENDING,1360,73,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 08:57:00,Second Class

In [8]:
dataset.drop(
    [
        "Customer Lname",
        "Customer Fname",
        "Customer Email",
        "Customer Password",
        "Department Name",
        "Customer Street",
        "Category Name",
        "Product Image",
        "Product Name"
    ],
    axis=1,
    inplace=True
)

In [9]:
days_pred_df = dataset.loc[:, [
    "Days for shipping (real)",
    "Category Id",
    "Customer City",
    "Customer Country",
    "Customer State",
    "Customer Zipcode",
    "Market",
    "Order City",
    "Order Country",
    "Order Region",
    "Order State",
    "Shipping Mode",
    "Order Item Quantity"
]]
days_pred_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172765 entries, 0 to 180518
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Days for shipping (real)  172765 non-null  int64
 1   Category Id               172765 non-null  int64
 2   Customer City             172765 non-null  object
 3   Customer Country          172765 non-null  object
 4   Customer State            172765 non-null  object
 5   Customer Zipcode          172762 non-null  float64
 6   Market                    172765 non-null  object
 7   Order City                172765 non-null  object
 8   Order Country             172765 non-null  object
 9   Order Region              172765 non-null  object
 10  Order State               172765 non-null  object
 11  Shipping Mode             172765 non-null  object
 12  Order Item Quantity       172765 non-null  int64
dtypes: float64(1), int64(3), object(9)
memory usage: 18.5+ MB

In [10]:
days_pred_df.isna().sum()

Days for shipping (real)    0
Category Id                 0
Customer City               0
Customer Country            0
Customer State              0
Customer Zipcode            3
Market                      0
Order City                  0
Order Country               0
Order Region                0
Order State                 0
Shipping Mode               0
Order Item Quantity         0
dtype: int64

In [11]:
# Imputing missing numerical data
from sklearn.impute import SimpleImputer
import numpy as np

# Create a SimpleImputer Class
imputer = SimpleImputer(missing_values=np.NaN, strategy="mean")

# Fit the column to the object
column = "Customer Zipcode"
imputer = imputer.fit(dataset.loc[:, [column]])

# Transform the DataFrames column with the fitted data
days_pred_df.loc[:, column] = imputer.transform(dataset.loc[:, [column]])

In [12]:
days_pred_df.drop("Customer Zipcode", axis=1, inplace=True)

In [15]:
from sklearn.preprocessing import OneHotEncoder

one_hot = OneHotEncoder()
encoded = one_hot.fit_transform(days_pred_df[["Order City"]])
encoded.toarray().shape

(172765, 3585)

In [16]:
categorical_cols = [
    "Category Id",
    "Customer City",
    "Customer Country",
    "Customer State",
    "Market",
    "Order City",
    "Order Country",
    "Order State",
    "Order Region",
    "Shipping Mode"
]
encoded_days_pred_df = pd.get_dummies(days_pred_df, columns=categorical_cols)
encoded_days_pred_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 172765 entries, 0 to 180518
Columns: 5528 entries, Days for shipping (real) to Shipping Mode_Standard Class
dtypes: int64(2), uint8(5526)
memory usage: 914.4 MB

In [59]:
X = encoded_days_pred_df.iloc[:, 1:].head(10000)
y = encoded_days_pred_df.iloc[:, 0].head(10000)
X.shape

(10000, 5527)

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [22]:
# Create a Random Forest regressor
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42, max_depth=16)

# Fit the model on the training data
rf_regressor.fit(X_train, y_train)

RandomForestRegressor(max_depth=16, random_state=42)

In [17]:
# Predict on the test data
y_pred = rf_regressor.predict(X_test)

# Calculate mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.695663594492131

In [18]:
rf_regressor.predict(encoded_days_pred_df.iloc[0:10, 1:])

array([4.00066868, 4.01073937, 3.99986779, 3.99062342, 4.00405339,
       2.        , 2.        , 3.96800462, 2.        , 3.98979709])

In [19]:
y[0:10]

0     3
1     5
2     4
3     3
4     2
6     2
7     2
8     3
9     2
11    5
Name: Days for shipping (real), dtype: int64

In [18]:
import torch
import torch.nn as nn
import torch.optim as optim

In [23]:
# Convert data to PyTorch tensors
X_tensor = torch.tensor(X.values, dtype=torch.float32)
y_tensor = torch.tensor(y.values, dtype=torch.float32).unsqueeze(1)  # Add a dimension for regression

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_tensor, y_tensor, test_size=0.2, random_state=42)

In [35]:
from SimpleNeuralNet import NeuralNetwork

In [36]:
# Set hyperparameters
input_dim = X.shape[1]  # Total number of input features
hidden_dim = 64

# Instantiate the model
model = NeuralNetwork(input_dim, hidden_dim)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [37]:
# Training loop
num_epochs = 300
for epoch in range(num_epochs):
    model.train()
    optimizer.zero_grad()
    outputs = model(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/300], Loss: 13.6377
Epoch [20/300], Loss: 10.1167
Epoch [30/300], Loss: 6.6722
Epoch [40/300], Loss: 3.9740
Epoch [50/300], Loss: 2.5431
Epoch [60/300], Loss: 2.1712
Epoch [70/300], Loss: 2.0879
Epoch [80/300], Loss: 1.9520
Epoch [90/300], Loss: 1.8367
Epoch [100/300], Loss: 1.7554
Epoch [110/300], Loss: 1.6835
Epoch [120/300], Loss: 1.6191
Epoch [130/300], Loss: 1.5628
Epoch [140/300], Loss: 1.5124
Epoch [150/300], Loss: 1.4672
Epoch [160/300], Loss: 1.4265
Epoch [170/300], Loss: 1.3897
Epoch [180/300], Loss: 1.3565
Epoch [190/300], Loss: 1.3265
Epoch [200/300], Loss: 1.2993
Epoch [210/300], Loss: 1.2747
Epoch [220/300], Loss: 1.2525
Epoch [230/300], Loss: 1.2323
Epoch [240/300], Loss: 1.2141
Epoch [250/300], Loss: 1.1976
Epoch [260/300], Loss: 1.1827
Epoch [270/300], Loss: 1.1692
Epoch [280/300], Loss: 1.1570
Epoch [290/300], Loss: 1.1459
Epoch [300/300], Loss: 1.1358

In [38]:
# Evaluation
model.eval()
with torch.no_grad():
    y_pred = model(X_test)
    mse = mean_squared_error(y_test.numpy(), y_pred.numpy())
    print(f"Mean Squared Error: {mse:.4f}")

Mean Squared Error: 1.8228

In [56]:
import numpy as np
prediction = model(torch.Tensor(X[0:10].to_numpy())).flatten().detach().numpy()
np.concatenate((prediction.reshape(-1, 1), y[0:10].to_numpy().reshape(-1,1)), axis=1)

array([[4.22639751, 3.        ],
       [4.35393047, 5.        ],
       [4.41334343, 4.        ],
       [3.7277844 , 3.        ],
       [3.79738879, 2.        ],
       [2.48560667, 2.        ],
       [2.12850475, 2.        ],
       [3.9225862 , 3.        ],
       [2.96319747, 2.        ],
       [5.12047911, 5.        ]])

In [53]:
y[0:10].to_numpy().reshape(1,-1)

array([[3, 5, 4, 3, 2, 2, 2, 3, 2, 5]], dtype=int64)

In [27]:
# Set hyperparameters
input_dim = X.shape[1]  # Total number of input features
hidden_dim = 128

# Instantiate the model
model128 = NeuralNetwork(input_dim, hidden_dim)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model128.parameters(), lr=0.001)

In [29]:
# Training loop
num_epochs = 300
for epoch in range(num_epochs):
    model128.train()
    optimizer.zero_grad()
    outputs = model128(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [10/300], Loss: 13.4848
Epoch [20/300], Loss: 9.4330
Epoch [30/300], Loss: 5.4966
Epoch [40/300], Loss: 2.9182
Epoch [50/300], Loss: 2.2124
Epoch [60/300], Loss: 2.1635
Epoch [70/300], Loss: 1.9580
Epoch [80/300], Loss: 1.8207
Epoch [90/300], Loss: 1.7335
Epoch [100/300], Loss: 1.6495
Epoch [110/300], Loss: 1.5796
Epoch [120/300], Loss: 1.5189
Epoch [130/300], Loss: 1.4650
Epoch [140/300], Loss: 1.4175
Epoch [150/300], Loss: 1.3752
Epoch [160/300], Loss: 1.3377
Epoch [170/300], Loss: 1.3042
Epoch [180/300], Loss: 1.2743
Epoch [190/300], Loss: 1.2475
Epoch [200/300], Loss: 1.2233
Epoch [210/300], Loss: 1.2012
Epoch [220/300], Loss: 1.1810
Epoch [230/300], Loss: 1.1622
Epoch [240/300], Loss: 1.1449
Epoch [250/300], Loss: 1.1288
Epoch [260/300], Loss: 1.1138
Epoch [270/300], Loss: 1.0998
Epoch [280/300], Loss: 1.0868
Epoch [290/300], Loss: 1.0746
Epoch [300/300], Loss: 1.0632

In [31]:
# Evaluation
model128.eval()
with torch.no_grad():
    y_pred = model128(X_test)
    mse = mean_squared_error(y_test.numpy(), y_pred.numpy())
    print(f"Mean Squared Error: {mse:.4f}")

Mean Squared Error: 1.8404

In [57]:
import numpy as np
prediction = model128(torch.Tensor(X[0:10].to_numpy())).flatten().detach().numpy()
np.concatenate((prediction.reshape(-1, 1), y[0:10].to_numpy().reshape(-1,1)), axis=1)

array([[4.27036047, 3.        ],
       [4.36266184, 5.        ],
       [4.42785263, 4.        ],
       [3.70751047, 3.        ],
       [3.6869328 , 2.        ],
       [2.44893765, 2.        ],
       [2.11158586, 2.        ],
       [4.02932978, 3.        ],
       [3.03222251, 2.        ],
       [5.13543272, 5.        ]])

In [58]:
torch.save(model128.state_dict(), 'model128.pth')

In [81]:
import requests

# URL of your Flask app's predict route
url = 'http://localhost:5000/predict'  # Update with your actual URL

# Sample input data in JSON format
input_data = {
    "input_data": [int(i) for i in X_tensor[0]]  # Adjust based on your model's input format
}

# Send POST request
response = requests.post(url, json=input_data)

if response.status_code == 200:
    data = response.json()
    predictions = data['predictions']
    print("Predictions:", predictions)
else:
    print("Error:", response.text)

Predictions: [4.270360946655273]